Infra: Refactor label synchronization in workflow
Change from `for` to `while` loop for label synchronization to handle multiline label strings correctly. Added error handling for `gh pr edit` command to provide feedback if label addition fails.

diff --git a/.github/workflows/sync-issue-with-pr.yaml b/.github/workflows/sync-issue-with-pr.yaml
--- a/.github/workflows/sync-issue-with-pr.yaml
+++ b/.github/workflows/sync-issue-with-pr.yaml
@@ -69,11 +69,12 @@ jobs:
             fi
 
             # Copy only major, minor, and patch labels from the issue to the PR
-            for LABEL in $LABELS
-            do
-              if [[ "$LABEL" == "major" || "$LABEL" == "minor" || "$LABEL" == "patch" ]]; then
-                echo "Adding label $LABEL to PR"
-                gh pr edit ${{ github.event.pull_request.number }} --add-label "$LABEL"
+          while IFS= read -r LABEL; do
+            if [[ "$LABEL" == "major" || "$LABEL" == "minor" || "$LABEL" == "patch" ]]; then
+              echo "Adding label $LABEL to PR"
+              if ! gh pr edit ${{ github.event.pull_request.number }} --add-label "$LABEL"; then
+                echo "Failed ot add label '$LABEL' to PR"
               fi
-            done
-          done
+            fi
+          done <<< "$LABELS"
+          echo >> .github/workflows/sync-issue-with-pr.yaml
